version: "3.8"

services:
  postgres:
    image: postgres
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
    ports:
      - 5432:5432
    volumes:
      - ./src/database:/docker-entrypoint-initdb.d

  app:
    depends_on:
      - postgres
    links:
      - postgres
    build: .
    env_file: ./.env
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
